name: pmsn20232
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-215.0.dev <4.0.0'

dependencies:
  flutter_slider_drawer: ^2.1.3
  day_night_switcher: ^0.2.0+1
  shared_preferences: ^2.2.1
  concentric_transition: ^1.0.3
  lottie: ^2.6.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images
    - assets/animation
